version: '3.9'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - web_app
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_PROD_NAME}
      - POSTGRES_USER=${DB_PROD_USER}
      - POSTGRES_PASSWORD=${DB_PROD_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_user -d your_db_name"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka1:
    image: 'docker.io/bitnami/kafka:latest'
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      # Внешний листенер для клиентов
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://${KAFKA_URL}:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Безопасность
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CLIENT_USERS=${KAFKA_CLIENT_USERS}
      - KAFKA_CLIENT_PASSWORDS=${KAFKA_CLIENT_PASSWORDS}
      # SSL настройки
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KAFKA_CFG_SSL_KEY_PASSWORD=${KEYSTORE_PASSWORD}
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      # Настройки производительности
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_HEAP_OPTS=-Xmx4G -Xms4G
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_MESSAGE_MAX_BYTES=31457280
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=31457280
      # Мониторинг
      - KAFKA_CFG_METRIC_REPORTERS=org.apache.kafka.common.metrics.JmxReporter
    volumes:
      - ./certs:/opt/bitnami/kafka/config/certs
    networks:
      - web_app
    depends_on:
      - zookeeper

  kafka2:
    image: 'docker.io/bitnami/kafka:latest'
    container_name: kafka2
    ports:
      - "9094:9094"
      - "9095:9095"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      # Внешний листенер для клиентов
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9094,EXTERNAL://${KAFKA_URL}:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Безопасность
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CLIENT_USERS=${KAFKA_CLIENT_USERS}
      - KAFKA_CLIENT_PASSWORDS=${KAFKA_CLIENT_PASSWORDS}
      # SSL настройки
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KAFKA_CFG_SSL_KEY_PASSWORD=${KEYSTORE_PASSWORD}
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      # Настройки производительности
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=2
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_HEAP_OPTS=-Xmx4G -Xms4G
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_MESSAGE_MAX_BYTES=31457280
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=31457280
      # Мониторинг
      - KAFKA_CFG_METRIC_REPORTERS=org.apache.kafka.common.metrics.JmxReporter
    volumes:
      - ./certs:/opt/bitnami/kafka/config/certs
    networks:
      - web_app
    depends_on:
      - zookeeper

  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web_app
  
  prometheus:
    image: 'docker.io/bitnami/prometheus:latest'
    container_name: prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:ro
      - prometheus_data:/opt/bitnami/prometheus/data
    command:
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus.yml'
      - '--storage.tsdb.path=/opt/bitnami/prometheus/data'
      - '--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries'
      - '--web.console.templates=/opt/bitnami/prometheus/conf/consoles'
    restart: unless-stopped
    networks:
      - web_app
  
  grafana:
    image: 'docker.io/bitnami/grafana:latest'
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=12345
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/opt/bitnami/grafana/data
      - ./grafana/provisioning:/opt/bitnami/grafana/conf/provisioning
    restart: unless-stopped
    networks:
      - web_app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./app:/app
      - ./config.py:/app/config.py 
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - zookeeper
      - kafka1
      - kafka2
      - redis
    networks:
      - web_app
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
    networks:
      - web_app
    
networks:
  web_app:

volumes:
  zookeeper_data:
  redis_data:
  prometheus_data:
  grafana_data:
  postgres_data: