"""add index to token

Revision ID: 2493e0cc7b55
Revises: 122806c0c774
Create Date: 2024-12-29 18:50:13.363346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2493e0cc7b55"
down_revision: Union[str, None] = "122806c0c774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_tokens_access_token"), "tokens", ["access_token"], unique=False
    )
    op.create_index(
        op.f("ix_tokens_refresh_token"), "tokens", ["refresh_token"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_refresh_token"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_access_token"), table_name="tokens")
    # ### end Alembic commands ###
