"""added user_id as foreign key in tokens

Revision ID: 9042f0f114e3
Revises: b045b5139858
Create Date: 2024-09-18 18:13:02.296961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9042f0f114e3'
down_revision: Union[str, None] = 'b045b5139858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="user_id::integer")
    op.drop_index('ix_tokens_user_id', table_name='tokens')
    op.create_unique_constraint(None, 'tokens', ['user_id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_index('ix_tokens_user_id', 'tokens', ['user_id'], unique=True)
    op.alter_column('tokens', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
