"""adding paypal plans

Revision ID: ab97d874ce16
Revises: c1b45243f353
Create Date: 2025-02-13 17:45:09.454074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab97d874ce16"
down_revision: Union[str, None] = "c1b45243f353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paypal_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_paypal_plans_id"), "paypal_plans", ["id"], unique=False)
    op.create_index(
        op.f("ix_paypal_plans_plan_id"), "paypal_plans", ["plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paypal_plans_plan_id"), table_name="paypal_plans")
    op.drop_index(op.f("ix_paypal_plans_id"), table_name="paypal_plans")
    op.drop_table("paypal_plans")
    # ### end Alembic commands ###
